services:
  library:
    image: node:alpine
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    ports:
      - 80:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: sleep infinity
    depends_on:
      - storage
  storage:
    image: redis
    volumes:
      - ./data:/data